return {
	"elentok/togglr.nvim",
	keys = { "<leader>ot" },
	opts = {
		key = "<Leader>ot",
		register = "t",
		debug = false,
		values = {
			["true"] = "false",
			["True"] = "False",
			["yes"] = "no",
			["on"] = "off",
			["enabled"] = "disabled",
			["enable"] = "disable",
			["left"] = "right",
			["top"] = "bottom",
			["up"] = "down",
			["addClass"] = "removeClass",
			["column"] = "row",
			["back"] = "fwd",
			["const"] = "let",
			["light"] = "dark",
			["0"] = "1",
			["+"] = "-",
			[">"] = "<",
			[">="] = "<=",
			["=="] = "!=",
		},
	},
	require("Configs.keymaps").Togglr(),
}
