return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPost" },
	cmd = { "TSInstall", "TSBufEnable", "TSBufDisable", "TSModuleInfo" },
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"regex",
			"bash",
			"jsdoc",
			"html",
			"css",
			"scss",
			"javascript",
			"json",
			"jsonc",
			"typescript",
			"tsx",
			"sql",
			"php",
			"yaml",
			-- "prisma",
			"markdown",
			"markdown_inline",
			-- "svelte",
			-- "graphql",
			"lua",
			"vim",
			-- "dockerfile",
			-- "gitignore",
			"go",
			-- "http",
			-- "java",
			"rust",
			"query",
			"vimdoc",
			-- "astro",
			"c",
			"cpp",
			-- "csv",
			"python",
			-- "fish",
		},

		ignore_install = { "" },
		sync_install = false,
		auto_install = true,
		modules = {},

		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
		},
		indent = { enable = true },
		-- enable autotagging (w/ nvim-ts-autotag plugin)
		autotag = { enable = true },
		autopairs = { enable = true },
		-- List of parsers to ignore installing (or "all")
		textobjects = {
			select = { enable = false },
		},
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<bs>",
			},
		},
	},
}
